#Workflow name
name: CI/CD Pipeline
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  #Test's job
  tests:
    name: Unit tests
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
     # Checkout code
     - uses: actions/checkout@v2
     
     # Setup Java
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt' # See 'Supported distributions' for available options
         java-version: '11'
         
     # Build
     - name: Build the project
       run: mvn -B -DskipTests install
       
     # Build Docker image  
     - name: Build Docker
       run: mvn jib:dockerBuild
