#Workflow name
name: Build Spring Boot application with GitHub Actions
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push:
    branches:
      - main
jobs:
  # Build's job
  build:
    name: Build the application
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
     # Checkout code
     - uses: actions/checkout@v2
     # Setup Java
     - uses: actions/setup-java@v2
       with:
         distribution: 'adopt' # See 'Supported distributions' for available options
         java-version: '11'
         cache: 'maven'
         server-id: ghcr.io
         server-username: ${{secrets.DOCKER_USERNAME}}
         server-password: ${{secrets.DOCKER_PASSWORD}}
     # Build Spring boot
     - name: Build the project
       run: mvn -B -DskipTests install
     # Login to Docker registry  
     - name: Docker Login
       uses: docker/login-action@v1.10.0
       with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ghcr.io
        # Username used to log against the Docker registry
        username: ${{secrets.DOCKER_USERNAME}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKER_PASSWORD}}
        # Log out from the Docker registry at the end of a job
        logout: true
     # Build Docker image  
     - name: Build Docker
       run: mvn jib:build
